#!/bin/bash

# ensure we have epel-release
cat <<EOM >/etc/yum.repos.d/epel-bootstrap.repo
[epel]
name=Bootstrap EPEL
mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-\$releasever&arch=\$basearch
failovermethod=priority
enabled=0
gpgcheck=0
EOM

yum --enablerepo=epel -y install epel-release
rm -f /etc/yum.repos.d/epel-bootstrap.repo


# ensure we have ius-release
cat <<EOM >/etc/yum.repos.d/ius-bootstrap.repo
[ius]
name=Bootstrap IUS
baseurl=http://dl.iuscommunity.org/pub/ius/stable/Redhat/\$releasever/\$basearch/
failovermethod=priority
enabled=0
gpgcheck=0
EOM

yum --enablerepo=ius -y install ius-release
rm -f /etc/yum.repos.d/ius-bootstrap.repo


# Secure permissions
chmod -R u=rwx,g=rx,o= /nimble

# Install all of our packages below
yum -y install \
vim gcc gcc-c++ make autoconf yum-plugin-replace pam-devel \
httpd httpd-devel libcap-devel mod_ssl \
mysql-server mysql \
php php-devel php-fpm php-mysql php-gd php-mcrypt php-xmlrpc php-xml php-mbstring php-pear \
mydns mydns-mysql \
postfix dovecot dovecot-mysql \
vsftpd


# We don't like selinux... apache runs as multiple users... this is a multi-user system... and I'm lazy
setenforce 0
sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/sysconfig/selinux


# Allow our services to be accessible through the firewall.

iptables -I INPUT -p tcp --dport 80 -j ACCEPT
iptables -I INPUT -p tcp --dport 443 -j ACCEPT
iptables -I INPUT -p tcp --dport 1337 -j ACCEPT
iptables -I INPUT -p tcp --dport 1338 -j ACCEPT
iptables -I INPUT -p tcp --dport 3306 -j ACCEPT


iptables -I INPUT -p tcp --dport 21 -j ACCEPT
iptables -I INPUT -p tcp --dport 22 -j ACCEPT
iptables -I INPUT -p tcp --dport 25 -j ACCEPT
iptables -I INPUT -p tcp --dport 110 -j ACCEPT
iptables -I INPUT -p tcp --dport 143 -j ACCEPT
iptables -I INPUT -p tcp --dport 487 -j ACCEPT
iptables -I INPUT -p tcp --dport 993 -j ACCEPT
iptables -I INPUT -p tcp --dport 995 -j ACCEPT

service iptables save


# start or restart sasl... we fucking want this to run.
if [ -f /var/run/saslauthd/saslauthd.pid ]; then
	service saslauthd restart
else
	service saslauthd start
fi

# make sure sasl is ALWAYS on. we love sasl... sasl is our friend.
chkconfig saslauthd on


# Upgrade to mysql56u so innodb doesn't suck..
yum -y replace mysql --replace-with mysql56u

# setup apache
/nimble/httpd/setup

# setup mysqld
/nimble/mysql/setup

# setup mydns
/nimble/mydns/setup

# setup mail
/nimble/mail/setup

# setup ftp
/nimble/vsftpd/setup

# setup nimble webpanel
/nimble/webpanel/setup


